# Generated by Django 2.1.5 on 2019-02-03 18:33

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
