# Generated by Django 2.1.5 on 2019-02-03 18:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190203_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
